id: IBC9F10C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T14:09:56+00:00'
last_modified: '2022-06-08T02:09:41.105921+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W9810
  title: ལམ་རིམ་དམར་ཁྲིད་བདེ་ལམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    051E:
      image_group_id: I1KG505
      title: ''
      total_pages: 66
      order: 1
      base_file: 051E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
