id: IBC9F10C0
legacy_id: P004591
ocr_import_info:
  bdrc_scan_id: W9810
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T14:09:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:11:55.886855+00:00'
last_modified: 2022-09-04 13:12:01.105815
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W9810
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW9810
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་རིམ་དམར་ཁྲིད་བདེ་ལམ།
  author: པཎ་ཆེན་བློ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.6559075348977038
  ocr_word_median_confidence_index: 0.7400000095367432
quality: null
bases:
  I1KG505:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG505
      total_pages: 66
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG505.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6559075348977038
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
